### ISSUE TITLE
Use separate fields for given and last names in CITATION.cff

### ISSUE THREAD

**Issue by NeuroShepherd** [lmu-osc/introduction-to-renv#39]
For better parsing, particularly on Zenodo, should use this format:

```
authors:
  - family-names: Druskat
    given-names: Stephan
    orcid: https://orcid.org/1234-5678-9101-1121
```
